server:
  port: 8100

spring:
  application:
    name: kube-manager
  datasource:
    url: jdbc:mysql://47.100.137.154:3306/kube_manager?serverTimezone=Asia/Shanghai
    hikari:
      username: kube_manager
      password: Kube123!@#
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
  messages:
    basename: messages/messages
    encoding: utf-8
    use-code-as-default-message: true

logging:
  level:
    com.cgm.kube.account: debug
    com.cgm.kube.client: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
